### ISSUE TITLE
Do you have a complete example about  spring-cloud-stream-binder-jms with ActiveMQ?

### ISSUE THREAD

**Issue by waylau** [mohammedamineboutouil/spring-cloud-stream-binder-jms#2]
I am new to spring-cloud-stream-binder-jms.
I try to write a example about  spring-cloud-stream-binder-jms with ActiveMQ, but failed.
Anybody help?

**Comment by realboutouil** [comment]
Have you tried with ibm mq use the following configuration   
add  
implementation "com.ibm.mq:mq-jms-spring-boot-starter:$springMQJmsVersion"

```
// application.yml
## IBM MQ ENV ##
IBMMQ_HOST: localhost
IBMMQ_PORT: 1414
IBMMQ_USER: admin
IBMMQ_PASSWORD: passw0rd
IBMMQ_QUEUE_MANAGER: QM1
IBMMQ_CHANNEL: DEV.ADMIN.SVRCONN

ibm:
  mq:
    user: ${IBMMQ_USER}
    password: ${IBMMQ_PASSWORD}
    conn-name: ${IBMMQ_HOST}(${IBMMQ_PORT})
    queue-manager: ${IBMMQ_QUEUE_MANAGER}
    channel: ${IBMMQ_CHANNEL}

// docker-compose.yml
  ibmmq:
    image: ibm-messaging/mq
    container_name: ibm-mq
    ports:
      - "1414:1414"
      - "9443:9443"
      - "9157:9157"
    environment:
      LICENSE: "accept"
      MQ_QMGR_NAME: "QM1"
    #    volumes:
    #      - ~/mqm-data:/var/mqm
    restart: unless-stopped
```

**Comment by waylau** [comment]
@mohammedamineboutouil   thank you very much for your reply!

I  have wrote a example about spring-cloud-stream-binder-jms with ActiveMQ，it works fine.
https://github.com/waylau/spring-cloud-stream-tutorial/blob/main/docs/spring-initializr-cloud-stream-jms.md
